### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by rafael-abuawad** [kristoferlund/ic-siwe-react-demo-ts#1]
I'm trying to use this inside my project (Motoko) i just need to add the smart contract to my `dfx.json` config? And use the frontend package with reac? Is that it?

Thank you

**Comment by kristoferlund** [comment]
Yep. 

1. Add provider canister to dfx.json
2. Add `SiweIdentityProvider` to main.tsx
3. Use the `useSiweIdentity()` hook.

Please post additional questions in the Dfinity forum: https://forum.dfinity.org/

Thanks.

**Comment by kristoferlund** [comment]
(easiest way to get started is to fork this repo)

**Comment by rafael-abuawad** [comment]
> (easiest way to get started is to fork this repo)

Ok thank you! I just wanted to understand how it works from scratch
